# .streamlit/config.toml

[theme]
base="dark"                         # Wähle "light" oder "dark"
primaryColor="#419AD9"              # Primäre Farbe für Buttons und Highlights
backgroundColor= "#416AD9"           # Hintergrundfarbe der App
secondaryBackgroundColor="#899FD9"  # Hintergrundfarbe der Seitenleiste
textColor="#FFFFFF"                 # Haupttextfarbe
font="monospace"                    # Schriftart